### ISSUE TITLE
Infinite fluid dupe from Lab Oven

### ISSUE THREAD

**Issue by OrdinatorStouff** [al132/ATM-Rockhounding#2]
Put some fluid into lab oven input tank. Pump out from that input tank infinitely. Screenshot is an example, water was placed in lab oven input tank and can be pumped out without ever depleting that input tank volume.

![2017-02-09_20 38 40](https://cloud.githubusercontent.com/assets/6283913/22813652/737f853c-ef0a-11e6-8d1e-3bfa608ac53e.png)

**Comment by al132** [comment]
This is an Embers bug. I was able to duplicate it with only Ender IO and Embers. However, as best as I know Embers for 1.10 is no longer being maintained, so most likely i'll just remove them from expert and make sure there is a valid early game alternative for piping. 
![2017-02-19_23 17 22](https://cloud.githubusercontent.com/assets/16395640/23112926/e0ed1bb0-f6f9-11e6-9404-c26dbda1848e.png)
